name: Deploy to Staging Server

on:
  push:
    branches: [main]

jobs:
  redeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Decode SSH key
        run: |
          echo "${{secrets.SSH_VM_CICD}}" &> ~/ssh_key
          mkdir -p /home/runner.sh
          touch /home/runner/.ssh/known_hosts
          echo "${{secrets.KNOWN_HOSTS}}" &> /home/runner/.ssh/known_hosts
          chmod 700 /home/runner/ssh_key
          ssh -i ~/ssh_key ubuntu@52.71.184.107 -t cd vm_hosting_cicd && git pull origin main && export PATH=/home/ubuntu/.nvm/versions/node/v22.18.0/bin/npm && npm install -g pnpm && pnpm install && pnpm run build && pm2 restart be-server && pm2 restart fe-server && pm2 restart ws-server
