name: Deploy to staging
on:
  push:
    branches: [ main ]

jobs:
  redeploy_everything:
    runs-on: ubuntu-latest
    steps:
      - name: Decode and write SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_VM_CICD }}" | base64 -d > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 52.71.184.107 >> ~/.ssh/known_hosts

      - name: Deploy to staging server
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@52.71.184.107 "
            cd vm_hosting_cicd && \
            export PATH=/home/ubuntu/.nvm/versions/node/v22.18.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin && \
            npm install -g pnpm && \
            pnpm install && \
            pnpm run build && \
            pm2 restart fe-server && \
            pm2 restart http-server && \
            pm2 restart ws-server
          "
